# Generated by Django 5.0.1 on 2024-02-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('discounted_price', models.CharField(max_length=10)),
                ('actual_price', models.CharField(max_length=10)),
                ('discount_percentage', models.CharField(max_length=5)),
                ('rating', models.FloatField()),
                ('rating_count', models.IntegerField()),
                ('about_product', models.TextField()),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('review_id', models.CharField(max_length=20)),
                ('review_title', models.CharField(max_length=255)),
                ('review_content', models.TextField()),
                ('img_link', models.URLField()),
                ('product_link', models.URLField()),
            ],
        ),
    ]
